package com.monichev.jmschat.server.ui;

import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.Insets;
import java.util.HashMap;
import java.util.Map;

import javax.swing.JButton;
import javax.swing.JComponent;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTabbedPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import javax.swing.WindowConstants;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.monichev.jmschat.entity.MessageEntity;
import com.monichev.jmschat.jms.ServerBroker;

import org.springframework.stereotype.Component;

@Component
public class MainWindow extends JFrame {
    private final ServerBroker broker;
    private JTextField nameTextField;
    private JTextArea textArea1;
    private JPanel rootPanel;
    private JTextField textField1;
    private JButton sendButton;
    private JTabbedPane chatTabbedPane;
    private final Map<String, Chat> chatMap = new HashMap<>();

    public MainWindow() throws Exception {
        this.broker = new ServerBroker(61616, this::messageReceived, System.out::println);
        setTitle("Server");
        setContentPane($$$getRootComponent$$$());
        setSize(400, 400);
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setLocationRelativeTo(null);
        setAlwaysOnTop(true);
        setVisible(true);
    }

    private void messageReceived(MessageEntity messageEntity) {
        String from = messageEntity.getFrom();
        Chat chat = chatMap.get(from);
        if (chat == null) {
            chat = new Chat(from, broker);
            chatTabbedPane.addTab(from, chat.$$$getRootComponent$$$());
            chatMap.put(from, chat);
        }
        chat.messageReceived(messageEntity);
    }

    {
        // GUI initializer generated by IntelliJ IDEA GUI Designer
        // >>> IMPORTANT!! <<<
        // DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(2, 2, new Insets(10, 10, 10, 10), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText("Name");
        rootPanel.add(label1,
                new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED,
                        GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        nameTextField = new JTextField();
        nameTextField.setEditable(false);
        nameTextField.setText("Server");
        rootPanel.add(nameTextField,
                new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW,
                        GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        chatTabbedPane = new JTabbedPane();
        rootPanel.add(chatTabbedPane, new GridConstraints(1, 0, 1, 2, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH,
                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }

}
